name: Adventures in Computing
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
paginate: 4
plugins: [jekyll-paginate]
url: https://adventuresincomputing.bajgier.net
excerpt_separator: <!--more-->