name: Adventures in Computing
title: Adventures in Computing
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]
paginate: 4
plugins: [jekyll-paginate]
url: https://adventuresincomputing.bajgier.net
locale: en_US
excerpt_separator: <!--more-->
timezone: America/New_York
theme:
  description: "A humble development blog"